name: "web_app"
mode: "dev"    # dev——进入开发模式     release——发布模式
port: 8080
version: "v0.0.1"
machine_id: 1
start_time: "2023-09-24"

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "hyx20040731"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "hyx20040731"
  db: 0
  pool_size: 100